---
characterClass: duelist
population: 100
skills: 75
generations: 50000
alterers:
  - type: neighbor
    probability: .05
  - type: mutator
    probability: .05
  - type: crossover
    probability: .05
evaluators:
  - expression: passiveSkillCount
  - expression: strength * 10
  - expression: maximumLife * (1 + increasedMaximumLife) * 10
